[platformio]
src_dir = src

[env:fnirsi-138-pro]
platform = ststm32
framework = arduino
board = genericSTM32F103C8
board_build.core = maple
lib_ldf_mode = deep+
build_flags =
  -Isrc
lib_deps =
  adafruit/Adafruit GFX Library@1.7.5

; Choose and configure upload settings for your adapter when needed:
; upload_protocol = stlink
; upload_protocol = serial
; upload_port = COM3
